INFO Reading configuration /config/esphome/kitchen-ceiling-light.yaml...
INFO Configuration is valid!
esphome:
  name: kitchen-ceiling-light
  build_path: .esphome/build/kitchen-ceiling-light
  platformio_options: {}
  includes: []
  libraries: []
  name_add_mac_suffix: false
esp8266:
  board: esp01_1m
  framework:
    version: 3.0.2
    source: ~3.30002.0
    platform_version: platformio/espressif8266 @ 3.2.0
  restore_from_flash: false
  board_flash_mode: dout
logger:
  baud_rate: 115200
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  level: DEBUG
  logs: {}
  esp8266_store_log_strings_in_flash: true
api:
  port: 6053
  password: ''
  reboot_timeout: 15min
ota:
  password: 96313d90eb13b5347c2ca2c1d7173dc9
  safe_mode: true
  port: 8266
  reboot_timeout: 5min
  num_attempts: 10
wifi:
  ap:
    ssid: Kitchen-Ceiling-Light
    password: r9AmWSBDDmcY
    ap_timeout: 1min
  domain: .local
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  output_power: 20.0
  networks:
  - ssid: !secret 'wifi_ssid'
    password: !secret 'wifi_password'
    priority: 0.0
  use_address: kitchen-ceiling-light.local
captive_portal: {}
